spring.datasource.url=jdbc:postgresql://localhost:5432/tgBot
spring.datasource.username=tgBot
spring.datasource.password=qazedc
telegram.bot.token=8261349062:AAGb7U3vuEeG-s0cxmfEEoUSYX3573DoNr8

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.yml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true