# suppress inspection "UnusedProperty" for whole file
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tgBot}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.yml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.profiles.active=default